# Generated by Django 4.1.5 on 2023-01-20 00:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[\\w\\d]+$', 'Only alphanumeric characters are allowed.')])),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(unique=True)),
                ('consumption', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='meters.meter')),
            ],
        ),
    ]
