# Generated by Django 4.1.5 on 2023-01-20 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measure',
            old_name='date',
            new_name='timestamp',
        ),
    ]
